params = [
  ["HOW_MUCH_DOES_IT_COST_ACCORDION", "HOW_MUCH_DOES_IT_COST_TEXT", "HOW_MUCH_DOES_IT_COST"],
  ["CAN_I_HAVE_MANY_SCOOTERS_ACCORDION", "CAN_I_HAVE_MANY_SCOOTERS_TEXT", "CAN_I_HAVE_MANY_SCOOTERS"],
  ["HOW_TO_PAY_ACCORDION", "HOW_TO_PAY_TEXT", "HOW_TO_PAY"],
  ["CAN_I_ORDER_FOR_TODAY_ACCORDION", "CAN_I_ORDER_FOR_TODAY_TEXT", "CAN_I_ORDER_FOR_TODAY"],
  ["CAN_PROLONG_OR_RETURN_EARLIER_ACCORDION", "CAN_PROLONG_OR_RETURN_EARLIER_TEXT", "CAN_PROLONG_OR_RETURN_EARLIER"],
  ["CHARDER_WITH_SCOOTER_ACCORDION", "CHARDER_WITH_SCOOTER_TEXT", "CHARDER_WITH_SCOOTER"],
  ["CAN_CANCEL_ACCORDION", "CAN_CANCEL_TEXT", "CAN_CANCEL"],
  ["LEAVE_FAR_FROM_MKAD_ACCORDION", "LEAVE_FAR_FROM_MKAD_TEXT", "LEAVE_FAR_FROM_MKAD"]
]
